---
title: "EEG eyeblink detection"
output:
  html_document:
    df_print: paged
---

```{r}
#load libraries
library(foreign)
library(car)
library(fBasics)
library(caret)
library(corrplot)
library(randomForest)
library(e1071)
library(nnet)
library(gbm)
library(plyr)
library(kknn)
library(rpart)
```

```{r}
#Load data set from UCI repository
eegdat <- read.arff(("https://archive.ics.uci.edu/ml/machine-learning-databases/00264/EEG%20Eye%20State.arff"))
dim(eegdat)
head(eegdat)
```
```{r}
#explore data
str(eegdat)
```
```{r}
#summarize data
summary(eegdat)
```
```{r}
#function for visualizing attributes
vizser <- function(x,y,z,c){
  par(mar = c(2,2,2,2))
  par(mfrow = c(2,2))
  for(i in x:y){
    temp1 <- unlist(z[i])
    hist(temp1, col = c, xlab = "", main = 
           paste(colnames(z[i])))
    boxplot(temp1, col = c, xlab = "", main =
              paste(colnames(z[i])))
  }
}

#visualize raw data
par(mar = c(2,2,2,2))
par(mfrow = c(2,2))
vizser(1,14,eegdat,"cyan")
```
```{r}
#there are definite outliers in raw data
#find/remove outlier cases
#to do this generate zscores, remove instances with values +/- 4sds
eegdatz <- eegdat
eegdatz[c(1:14)] <- lapply(eegdatz[c(1:14)], function(x) c(scale(x, center = TRUE, scale = TRUE)))
eegdatz$ID <- seq.int(nrow(eegdatz))
head(eegdatz)
```
```{r}
#Identify rows with outliers: values +/- 4SDs
for(i in 1:14){
  nam <- paste("r", i, sep = "")
  out <- eegdatz[i] >=4 | eegdatz[i] <= -4
  out2 <- eegdatz$ID[out]
  assign(nam, out2)
}
out_all <- sort(unique(c(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14)))
out_all
```
```{r}
#view rows with outliers
eegout <-eegdatz[out_all,]
eegout
```
```{r}
#Remove rows with outliers from raw data
eegclean <- eegdat[-(out_all),]
summary(eegclean)
```
```{r}
#Visualise cleaned data: histograms & boxplots
vizser(1,14,eegclean,"orange")
```

```{r}
#function to return skew & kurtosis values
skrt <- function(x){
    for(i in 1:ncol(x)){
      if(is.factor(x[,i])){
        next
        } else {
           otpt <- c(colnames(x[i]),
                     round(skewness(x[,i]),2),
                     round(kurtosis(x[,i]),2))
           print(otpt)
          }
    }
  #return(data.frame(y))
}
skrt(eegclean)

```
```{r}
#Spearman correlation
eegcor <- round(cor(eegclean[1:14], method = "spearman"),2)
eegcor
eegcor_p <-cor.mtest(eegclean[1:14], method = "spearman", exact = NULL)
corrplot(eegcor, type = "lower", tl.col = "black",main = "Spearman Correlations", p.mat = eegcor_p$p, sig.level =  .05, insig = "blank", tl.srt = 45)
```
```{r}
#function to graph cleaned EEG signal by corresponding pairs
#differentiate eyes open/closed periods with blue bars in background
eegpairs <- function(x,y){
  ylim_min <- pmin(min(x), min(y))-50
  ylim_max <- pmax(max(x), max(y))+100
  xnam <- deparse(substitute(x))
  ynam <- deparse(substitute(y))
  xnam1 <- substring(xnam, regexpr("[$]", xnam)+1)
  ynam1 <- substring(ynam, regexpr("[$]", ynam)+1)
  plot(x, type = "l", col = "orange", ylim = range(c(ylim_min,ylim_max)), xlab = "Time", ylab = "Signal Amplitude")
  lines(y, type = "l", col = "olivedrab")
  legend(0,ylim_max, legend = c(paste0(xnam1), paste0(ynam1)), lwd = c(5,5), col = c("orange", "olivedrab"),bty = "n")
  xlft <- c(189, 1337, 2177, 2901, 3343, 5245, 6654, 11106, 12729, 12977, 14218, 14960)
  xrgt <- c(872, 1638, 2633, 2927, 4352, 5928, 9054, 12076, 12771, 13028, 14289, 14980)
  rect(xlft, ylim_min, xrgt, ylim_max, col = rgb(0,0,1.0, alpha=0.1), border = NA)
}
```
```{r}
#generate graphs for corresponding r/l sensor pairs
#using new 'eegpairs' function
eegpairs(eegclean$AF3, eegclean$AF4)
eegpairs(eegclean$F7, eegclean$F8)
eegpairs(eegclean$F3, eegclean$F4)
eegpairs(eegclean$FC5, eegclean$FC6)
eegpairs(eegclean$T7, eegclean$T8)
eegpairs(eegclean$P7, eegclean$P8)
eegpairs(eegclean$O1, eegclean$O2)
```
```{r}
#Apply index number to rows
eegclean$ID <- seq.int(nrow(eegclean))
summary(eegclean)

#Create train/test data sets
#Reserve 20% to test and 80% to train
set.seed(45)
indx <- createDataPartition(eegclean$ID, p = 0.8, list = FALSE)
train_data <- eegclean[indx,1:15]
test_data <- eegclean[-indx,1:15]
head(train_data)
head(test_data)

#Center/Scale train set, apply same process to test set
preproc <- preProcess(train_data, method = c("center", "scale"))
prep_train <- predict(preproc, train_data)
prep_test <- predict(preproc, test_data)
head(prep_train)
head(prep_test)

```
```{r}
#Create dataframe to store statistics from test set
best_models <- data.frame(modname = character(),
                          accuracy = integer(),
                          sensitiv = integer(),
                          specific = integer(),
                          precis = integer(),
                          f1 = integer(),
                          stringsAsFactors = FALSE
                          )

#function to record outcome variables
cm_out <- function(x,z){
  #round outcome vars and order in a list
  acc <- round(x$overall[1],4)
  sen <- round(x$byClass[1],4)
  spc <- round(x$byClass[2],4)
  prc <- round(x$byClass[5],4)
  ef1 <- round(x$byClass[7],4)
  
  y <- c(z, acc, sen, spc, prc, ef1)
  return(y)
}

#use Caret package to train models
#all models trained using same settings
trncntl <- trainControl(method = "repeatedcv", number = 10, verboseIter = FALSE, repeats = 3)

#log regression model
set.seed(42)
glm_formula <- train(eyeDetection ~., data = prep_train, 
                      method = "glm", family = "binomial",
                      trControl = trncntl, tuneLength = 10)
print(glm_formula)
pred_glm <- predict(glm_formula, newdata = prep_test, probility = TRUE)
cm_glm <- confusionMatrix(pred_glm, prep_test$eyeDetection)
print(cm_glm)

glm_out <- cm_out(cm_glm, "regression")

best_models[nrow(best_models)+1,] <- glm_out

best_models
```
```{r}
# CART decision tree
set.seed(42)
dt_formula <- train(eyeDetection ~., data = prep_train, 
                    method = "rpart",trControl = trncntl, 
                    tuneLength = 10)
print(dt_formula)
pred_dt <- predict(dt_formula, newdata = prep_test)
cm_dt <- confusionMatrix(pred_dt, prep_test$eyeDetection)
print(cm_dt)

dt_out <- cm_out(cm_dt, "d.tree")

best_models[nrow(best_models)+1,] <- dt_out
```
```{r}
# best RF model
set.seed(42)
rf_omni_trf <- tuneRF(prep_train[1:14], prep_train$eyeDetection, stepFactor = .5, doBest = TRUE)
pred_tunerf <- predict(rf_omni_trf, prep_test)
cm_tunerf <- confusionMatrix(pred_tunerf, prep_test$eyeDetection)
print(cm_tunerf)

rf_out <- cm_out(cm_tunerf, "rand.forest")

best_models[nrow(best_models)+1,] <- rf_out
```

```{r}
# best neural network
set.seed(42)
nn_grid <- expand.grid(size = c(40), decay = c(.35))
nn_formula = train(eyeDetection ~ ., 
                    data = prep_train, 
                    method = "nnet",
                    trControl=trncntl, 
                    tuneGrid = nn_grid5
                    )
print(nn_formula)
pred_nn <- predict(nn_formula, newdata = prep_test)
cm_nn <- confusionMatrix(pred_nn, prep_test$eyeDetection)
print(cm_nn)

nn_out <- cm_out(cm_nn, "n.network")

best_models[nrow(best_models)+1,] <- nn_out
```

```{r}
# best SVM
set.seed(42)
svm_grid <- expand.grid(sigma = c(.26), C = c(32.0))
svm_formula <- train(eyeDetection ~., 
                      data = prep_train, 
                      method = "svmRadial", 
                      trControl = trncntl, 
                      tuneGrid = svm_grid)
print(svm_formula)
pred_svm <- predict(svm_formula, newdata = prep_test)
cm_sv <- confusionMatrix(pred_svm, prep_test$eyeDetection)
print(cm_sv)

svm_out <- cm_out(cm_sv, "SVM")

best_models[nrow(best_models)+1,] <- svm_out 
```

```{r}
#KNN with kernel weighting (KKNN) -- Best model
set.seed(42)
knn_grid <- expand.grid(kmax = c(13),
                         distance = 2,
                         kernel = "triweight"
                         )
knn_formula <- train(eyeDetection ~.,
                      data = prep_train, 
                      method = "kknn", 
                      trControl = trncntl,
                      tuneGrid = knn_grid)
print(knn_formula)
pred_knn <- predict(knn_formula, newdata = prep_test)
cm_knn <- confusionMatrix(pred_knn, prep_test$eyeDetection)
print(cm_knn)

knn_out <- cm_out(cm_knn, "KKNN")

best_models[nrow(best_models)+1,] <- knn_out
```

```{r}
best_models
```




